### ISSUE TITLE
Is this the official CQ implementation?

### ISSUE THREAD

**Issue by una-dinosauria** [hellozting/CompositeQuantization#1]
Hi @hellozting!

Thanks so much for releasing your code!

I'm wondering whether this is the **official** CQ implementation that I can use to reproduce the results from [Zhang et al, ICML'14](http://proceedings.mlr.press/v32/zhangd14.pdf)? Ie, could you please confirm whether you are the first author of that paper?

Cheers,

**Comment by hellozting** [comment]
Yes, I am. You can use it to reproduce the results. I would be happy to answer if you met any questions. 

Thanks,

**Comment by una-dinosauria** [comment]
Thanks for the clarification
