### ISSUE TITLE
C++ standard?

### ISSUE THREAD

**Issue by una-dinosauria** [hellozting/CompositeQuantization#2]
I am having a very hard time compiling this code under ubuntu linux 16.04. In particular, it seems like this code is using multiple non-standard MSVC extensions that are not supported by g++; for example

* The `template<>` functions in `CQParameters.h` such as  https://github.com/hellozting/CompositeQuantization/blob/2456ae71d1c4da9f152e5e84073835ad67e6cfcb/ReleaseVersion/CQParameters.h#L111 are not allowed without a namespace in C++03 (see https://stackoverflow.com/a/3052604/1884420)
* The class `KMCException`, which extends `std::exception` is assuming that a constructor with arguments `(const char * const & info)` exists: https://github.com/hellozting/CompositeQuantization/blob/2456ae71d1c4da9f152e5e84073835ad67e6cfcb/ReleaseVersion/ClusterCommon.h#L32 but this is also specific to MSVC (see https://stackoverflow.com/a/28640662/1884420)

So, I'm wondering, 
1) is there a way to compile this using a standard c++ compiler (such as g++)?

If that's not the case, would you mind sharing the particular setup do you used to compile this code?

Thanks,

**Comment by hellozting** [comment]
Hi, I have written the text file HOW_TO_INSTALL as a document. Basically, it needs to use Cmake to generate the solutions.

Thanks,

**Comment by hellozting** [comment]
Also, the code is written under windows.

**Comment by una-dinosauria** [comment]
Thank you. I've been able to compile and run the code under windows.
