### ISSUE TITLE
Training on the base set?

### ISSUE THREAD

**Issue by una-dinosauria** [hellozting/CompositeQuantization#3]
Hi! Thanks again for releasing your code.

I've been running PQ and CQ using the provided `config.txt` file. In that file, the data seems to be loaded from the base set:

https://github.com/hellozting/CompositeQuantization/blob/1b363094b28839ada34299ee179cb99cf0414a20/ReleaseVersion/config.txt#L11

And training is done on that dataset. Is that what was done on the CQ paper from ICML 14?

I just want to point out that SIFT1M has a `learn` dataset, and the usual protocol is to train on that set, not on the base set.

**Comment by hellozting** [comment]
Hi, thanks for pointing it out.

Yes, I used the baseset as the training set for small datasets, e.g., MNIST, LABELME22K, 1MSIFT, 1MGIST. For the large dataset 1BSIFT, I used the first 1M training examples of baseset, as mentioned in the paper.

Thanks,

**Comment by una-dinosauria** [comment]
Thanks for clarifying.
