### ISSUE TITLE
recall is low?

### ISSUE THREAD

**Issue by xiongsilu** [hellozting/CompositeQuantization#5]
hi@hellozting, I use NCQ to train the dictionary_file and binary_codes_file , but the search result is bad. The recall@100 (T=1) is only 0.47. I wonder which step is wrong, here is my config.txt
`PQ=0
NCQ=1
CQ=0
Search=1

# global parameters
points_count=1000000
dictionaries_count=8
words_count=256
space_dimension=128
points_file=C:\Users\xxx\Downloads\sift\sift\sift_base.fvecs
output_file_prefix=C:\Users\xxx\Downloads\sift\sift\temp\
max_iter=30

# PQ parameters
distortion_tol=0.0001
read_partition=0
partition_file=
# if 101 then using closure cluster, else lloyd kmeans
kmeans_method=101

# NCQ and CQ parameters
num_sep=20
# initial from outside, if 1 then set the file name of dictinary and codes
initial_from_outside=0
dictionary_file=
binary_codes_file=

# CQ parameters
mu=0.0004

# Search parameters
queries_count=10000
groundtruth_length=100
result_length=100
queries_file=C:\Users\xxx\Downloads\sift\sift\sift_query.fvecs
groundtruth_file=C:\Users\xxx\Downloads\sift\sift\sift_groundtruth.ivecs
trained_dictionary_file=C:\Users\xxx\Downloads\sift\sift\temp\D
trained_binary_codes_file=C:\Users\xxx\Downloads\sift\sift\temp\B
output_retrieved_results_file=C:\Users\xxx\Downloads\sift\sift\temp\results`

And here is my distor_iter.txt:

`Iteration 0: distortion = 94339
Iteration 1: distortion = 67326.1
Iteration 2: distortion = 63031.2
Iteration 3: distortion = 61897.7
Iteration 4: distortion = 61423.5
Iteration 5: distortion = 61173.4
Iteration 6: distortion = 61024
Iteration 7: distortion = 60926.3
Iteration 8: distortion = 60858.5
Iteration 9: distortion = 60808.9
Iteration 10: distortion = 60772.7
Iteration 11: distortion = 60744.6
Iteration 12: distortion = 60723.2
Iteration 13: distortion = 60706.2
Iteration 14: distortion = 60693.1
Iteration 15: distortion = 60682.3
**Iteration 16: distortion = 262055**
Iteration 17: distortion = 90377.2
Iteration 18: distortion = 99150
Iteration 19: distortion = 96470
Iteration 20: distortion = 115715
Iteration 21: distortion = 98919.6
Iteration 22: distortion = 129036
Iteration 23: distortion = 118725
Iteration 24: distortion = 109591
Iteration 25: distortion = 111634
Iteration 26: distortion = 120328
Iteration 27: distortion = 110391
Iteration 28: distortion = 128095
Iteration 29: distortion = 115365`

Thanks to help.

**Comment by hellozting** [comment]
Hi, 

It seems that the optimization is not stable. 
NCQ adopts the closed-form solution to update dictionary. The matrix B*B^T might be ill conditioned which makes the optimization unstable.

Alternatively, I would suggest using CQ with the parameter mu set to be 0, which is equivalent to NCQ. The L-BFGS method used in CQ to update dictionary is more reliable. 

Thanks,

**Comment by xiongsilu** [comment]
Thanks and glad to see your reply! But I'm currently training on the Linux server. And I changed a lot of code to match the system ~ ~ . But your lbfgs.lib is unavailable on the Linux server . So I've removed some code like compositequantization.cpp and compositequantization.h temporarily. Would you share **libbfgs.so** which symbol table is the same as your lbfgs.lib ? Or please give some advice to me? Thank you.

**Comment by hellozting** [comment]
Hi,

Sorry that I don't have the experience of using lbfgs under Linux server. Would you please check the website https://github.com/chokkan/liblbfgs which might be helpful.

Thanks,

**Comment by xiongsilu** [comment]
Thanks, I try to modify the threshold (= 1) to filter small eigenvalues and add k-means iters when PQ initialized. And the performance is better (recall@1 T1 = 0.3 , recall@10T1 = 0.73 , recall@100 T1 = 0.975).But still is not good as paper. So I have two problems :
1 . How to understand the parameter **mu** and **distortion_tol** in config.txt ? And how to tuning the parameter when I use other dataset ?
2.  If I want to get more high recall,which should I do next ? try to L-bfgs? 
My problem may be a little bit more , thanks for your patience. :+1:

**Comment by hellozting** [comment]
Hi,

For the first problem, mu is a penalty parameter to make the optimization result satisfy the constant inter-dictionary-element-product. It is tuned using cross validation on a range, e.g, of {0.01,0.1,1,10,100}. distortion_tol is a parameter which is used to terminate the iteration if two consecutive objective value changed less than distortion_tol relatively. I didn't tune distortion_tol in the code. I don't think this would affect the results as long as it is set to be sufficiently small. 

I am not sure I understand the second problem. Could you please explain more. e.g., where do you modified the threshold to filter small eigenvalues? (I don't think I have this step)  and the performance is from CQ or NCQ with how many bits on which dataset? and where to try L-bfgs? (I used it in update dictionary step). 

Thanks,
