### ISSUE TITLE
Training on learn set gives low recall

### ISSUE THREAD

**Issue by una-dinosauria** [hellozting/CompositeQuantization#6]
Hi! -- Thanks for providing your code again.

I've adapted the this code to follow a more traditional protocol on SIFT1M, by
1. Training on the `learn` set
2. Using the learned codebooks to encode the `base` set
3. Compute recall on the `base` set wrt to the `queries`

The recall that I obtain is very low:
```
r@1 = .0871
r@2 = .1332
r@5 = .2211
...
```
Which is even lower than PQ. I'm wondering, is this lack of generalization when training on a small dataset something that you have observed? Or could it be that I am doing something wrong?

Cheers,

**Comment by hellozting** [comment]
Hi,

Are the results obtained under 64 bits? I didn't conduct such experiment on SIFT1M. But from the observation on similar experiments on SIFT1B, I don't think the results will be that low under 64 bits.

Two things that might be ignored in the second step when encoding the base set. 
1. the constant value, epsilon, should also be varied according to the binary code of the base set.
2. the binary code of base set is warm started by the PQ code (encode the base set with the learned PQ dictionary)

Thanks,
Ting
