### ISSUE TITLE
mu parameter for labelme22k

### ISSUE THREAD

**Issue by una-dinosauria** [hellozting/CompositeQuantization#7]
Hi @hellozting,

Sorry, hopefully this will be my last question.

I have found the value of `mu` for multiple datasets:

https://github.com/hellozting/CompositeQuantization/blob/1c7fdcdda224698dbc55a176afd517dad4e0bfcc/ReleaseVersion/CompositeQuantization.h#L329-L337

However, the paper also reported results on the LabelMe22K dataset. Do you have the value of `mu` that you used in those experiments?

Cheers,

**Comment by hellozting** [comment]
Hi,

The value of mu for LabelMe22K is 100. Sorry that I forgot to add it.

Thanks,

**Comment by una-dinosauria** [comment]
Thank you.
