### ISSUE TITLE
compile in linux

### ISSUE THREAD

**Issue by kr11** [hellozting/CompositeQuantization#8]
Thanks for your great work and I have reproduced results in your paper.
But I found this project used some methods which only run on Windows platform, how can I compile and run it in Linux?
Thanks again!

**Comment by hellozting** [comment]
Hi,
Sorry that I don't have the experience of using lbfgs under Linux server. Would you please check the website https://github.com/chokkan/liblbfgs which might be helpful.
Thanks,
